// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Setoran_API.NET.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20250612120141_refactor transaksi pembayaran relation")]
    partial class refactortransaksipembayaranrelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Setoran_API.NET.Models.DeviceToken", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdToken"));

                    b.Property<string>("IdPengguna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdToken");

                    b.HasIndex("IdPengguna");

                    b.ToTable("DeviceToken");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Diskon", b =>
                {
                    b.Property<int>("IdDiskon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDiskon"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text");

                    b.Property<int>("IdMotor")
                        .HasColumnType("integer");

                    b.Property<decimal>("JumlahDiskon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusDiskon")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalAkhir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdDiskon");

                    b.HasIndex("IdMotor");

                    b.ToTable("Diskon");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Mitra", b =>
                {
                    b.Property<int>("IdMitra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMitra"));

                    b.Property<string>("IdPengguna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IdMitra");

                    b.HasIndex("IdPengguna")
                        .IsUnique();

                    b.ToTable("Mitra");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Motor", b =>
                {
                    b.Property<int>("IdMotor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMotor"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HargaHarian")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdMitra")
                        .HasColumnType("integer");

                    b.Property<int?>("IdMotorImage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorBPKB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorSTNK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatNomor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusMotor")
                        .HasColumnType("integer");

                    b.Property<int>("Tahun")
                        .HasColumnType("integer");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Transmisi")
                        .HasColumnType("integer");

                    b.HasKey("IdMotor");

                    b.HasIndex("IdMitra");

                    b.HasIndex("IdMotorImage");

                    b.ToTable("Motor");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.MotorImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdMotor")
                        .HasColumnType("integer");

                    b.Property<string>("Left")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdMotor");

                    b.ToTable("MotorImage");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Notifikasi", b =>
                {
                    b.Property<int>("IdNotifikasi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotifikasi"));

                    b.Property<string>("DataNavigasi")
                        .HasColumnType("text");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text");

                    b.Property<string>("IdPengguna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Judul")
                        .HasColumnType("text");

                    b.Property<int>("Navigasi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WaktuNotifikasi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdNotifikasi");

                    b.HasIndex("IdPengguna");

                    b.ToTable("Notifikasi");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Pelanggan", b =>
                {
                    b.Property<int>("IdPelanggan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPelanggan"));

                    b.Property<string>("IdPengguna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorSIM")
                        .HasColumnType("text");

                    b.HasKey("IdPelanggan");

                    b.HasIndex("IdPengguna")
                        .IsUnique();

                    b.ToTable("Pelanggan");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Pembayaran", b =>
                {
                    b.Property<int>("IdPembayaran")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPembayaran"));

                    b.Property<int>("IdTransaksi")
                        .HasColumnType("integer");

                    b.Property<int>("MetodePembayaran")
                        .HasColumnType("integer");

                    b.Property<int>("StatusPembayaran")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TanggalPembayaran")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdPembayaran");

                    b.HasIndex("IdTransaksi")
                        .IsUnique();

                    b.ToTable("Pembayaran");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Transaksi", b =>
                {
                    b.Property<int>("IdTransaksi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransaksi"));

                    b.Property<int>("IdMotor")
                        .HasColumnType("integer");

                    b.Property<int>("IdPelanggan")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTransaksi");

                    b.HasIndex("IdMotor");

                    b.HasIndex("IdPelanggan");

                    b.ToTable("Transaksi");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Ulasan", b =>
                {
                    b.Property<int>("IdUlasan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUlasan"));

                    b.Property<int>("IdMotor")
                        .HasColumnType("integer");

                    b.Property<int>("IdPelanggan")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalUlasan")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUlasan");

                    b.HasIndex("IdMotor");

                    b.HasIndex("IdPelanggan");

                    b.ToTable("Ulasan");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Voucher", b =>
                {
                    b.Property<int>("IdVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVoucher"));

                    b.Property<string>("KodeVoucher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaVoucher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersenVoucher")
                        .HasColumnType("integer");

                    b.Property<int>("StatusVoucher")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalAkhir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdVoucher");

                    b.HasIndex("KodeVoucher")
                        .IsUnique();

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.VoucherUsed", b =>
                {
                    b.Property<int>("PelangganIdPelanggan")
                        .HasColumnType("integer");

                    b.Property<int>("VoucherIdVoucher")
                        .HasColumnType("integer");

                    b.HasKey("PelangganIdPelanggan", "VoucherIdVoucher");

                    b.HasIndex("VoucherIdVoucher");

                    b.ToTable("VoucherUsed");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Pengguna", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdGambar")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorKTP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorTelepon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Pengguna");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Setoran_API.NET.Models.DeviceToken", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Pengguna", "Pengguna")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("IdPengguna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Diskon", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Motor", "Motor")
                        .WithMany("Diskon")
                        .HasForeignKey("IdMotor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Mitra", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Pengguna", "Pengguna")
                        .WithOne("Mitra")
                        .HasForeignKey("Setoran_API.NET.Models.Mitra", "IdPengguna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Motor", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Mitra", "Mitra")
                        .WithMany()
                        .HasForeignKey("IdMitra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Setoran_API.NET.Models.MotorImage", "MotorImage")
                        .WithMany()
                        .HasForeignKey("IdMotorImage");

                    b.Navigation("Mitra");

                    b.Navigation("MotorImage");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.MotorImage", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Motor", "Motor")
                        .WithMany()
                        .HasForeignKey("IdMotor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Notifikasi", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Pengguna", "Pengguna")
                        .WithMany("Notifikasis")
                        .HasForeignKey("IdPengguna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Pelanggan", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Pengguna", "Pengguna")
                        .WithOne("Pelanggan")
                        .HasForeignKey("Setoran_API.NET.Models.Pelanggan", "IdPengguna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Pembayaran", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Transaksi", "Transaksi")
                        .WithOne("Pembayaran")
                        .HasForeignKey("Setoran_API.NET.Models.Pembayaran", "IdTransaksi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaksi");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Transaksi", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Motor", "Motor")
                        .WithMany()
                        .HasForeignKey("IdMotor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Setoran_API.NET.Models.Pelanggan", "Pelanggan")
                        .WithMany()
                        .HasForeignKey("IdPelanggan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");

                    b.Navigation("Pelanggan");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Ulasan", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Motor", "Motor")
                        .WithMany("Ulasan")
                        .HasForeignKey("IdMotor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Setoran_API.NET.Models.Pelanggan", "Pelanggan")
                        .WithMany()
                        .HasForeignKey("IdPelanggan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");

                    b.Navigation("Pelanggan");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.VoucherUsed", b =>
                {
                    b.HasOne("Setoran_API.NET.Models.Pelanggan", "Pelanggan")
                        .WithMany()
                        .HasForeignKey("PelangganIdPelanggan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Setoran_API.NET.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherIdVoucher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelanggan");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Motor", b =>
                {
                    b.Navigation("Diskon");

                    b.Navigation("Ulasan");
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Transaksi", b =>
                {
                    b.Navigation("Pembayaran")
                        .IsRequired();
                });

            modelBuilder.Entity("Setoran_API.NET.Models.Pengguna", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("Mitra");

                    b.Navigation("Notifikasis");

                    b.Navigation("Pelanggan");
                });
#pragma warning restore 612, 618
        }
    }
}
