name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          # Go to your app directory
          cd ~/Setoran-API.NET

          # Kill existing screen session if running
          if screen -list | grep -q "setoran"; then
            screen -S setoran -X quit
          fi

          # Pull latest updates
          git pull origin main

          # Start new screen session and run your app (adjust this command)
          screen -dmS setoran bash -c 'dotnet run --urls "https://0.0.0.0:5104"'
    - name: Verify deployment is live
      run: |
        sleep 60  # optional delay to allow restart
        curl -sSf https://${{ secrets.VPS_HOST }}:5104/health > /dev/null